### PR TITLE
Collect and report all missing required arguments, not just the first on...

### PR DESCRIPTION
**Pull request by matthewcummings**
Friendlier error message when there are 2+ required arguments, report all that are missing not just the first one.

### CODE REVIEW

**Comment by kbrock** [comment]
Thanks.


Have you put together any tests / do you have any specific use cases you want to handle?
In the mean time, I'll see if I can put some features together on this one

**Comment by kbrock** [comment]
Since there are a number of users who use trollop to parse sub commands, I'm not sure the implications of providing the multi details by default.

I'll try and move this around to add an option.
There are getting to be too many options, wonder if I can find a way to merge that check instead of adding yet another option/if.

**Comment by matthewcummings** [comment]
Sorry, I'm not sure why I didn't see your responses earlier.  I will dig into this a bit more.  When I looked, I didn't see any test checking errors at this level of granularity.  The main use case I wanted to cover is when you have 2+ required args, but don't realize it, then you add the first one because it's flagged then you get an error about the second etc etc.  Not a huge deal, it would just be cleaner to say up front "hey, you're missing X, Y, Z args, they're all required."

**Comment by kbrock** [comment]
I understand/like your use case. Sorry I haven't had the time to dig very deep into this one.

**Comment by matthewcummings** [comment]
No worries, I would have added a test but when I looked, it seemed like it was going to require quite a bit of scaffolding and I didn't have time to do that.  :)

**Pull request closed without merging**
