### PR TITLE
Rename project from trollop to optimist

### LINKED ISSUE #75: Project name change request
This is my favorite library for option parsing, but I am hesitant to use it in any sort of formal work environment because I know some people may find the project name offensive.

### PR DESCRIPTION
**Pull request by kbrock**
will need to:

- [ ] rename github project
- [ ] change awesome ruby
- [ ] put in a redirect in rubygems

I may have missed some

Fixes #75

### CODE REVIEW

**Comment by jrafanie** [comment]
Do we want to deprecate the old class?

Something like this:  https://github.com/thoughtbot/factory_bot/blob/master/lib/factory_girl.rb
In this way, the constant can stay around for a release or so?

**Comment by olivierlacan** [comment]
I support this. Having a gem referencing the old-timey word for slut is really not great.

**Comment by olivierlacan** [comment]
@kbrock The renaming mostly. I think it's fine to maintain backward compat to avoid putting people in messy situations.

**Comment by kbrock** [comment]
@jrafanie @Fryguy ok - added warning - you all ready to do this?

I'll need one of you to go into settings and rename this github project from `trollop` over to `optimist`.

**Comment by jrafanie** [comment]
> @jrafanie @Fryguy ok - added warning - you all ready to do this?

@kbrock what warning?

> I'll need one of you to go into settings and rename this github project from trollop over to optimist.

@Fryguy will have to do this, I don't have permission to do it.

**Pull request merged**
