### PR TITLE
add ability to give errors custom exit codes

### LINKED ISSUE #57: Exit code from educate
`Trollop.educate` exits with code `0`.  I would like to use Trollop in an existing script, but usage errors must exit with a code N != `0`.  As a workaround, I can reopen Trollop:

```ruby
module Trollop
  def self.educate_without_exiting
    @last_parser.educate
  end
end

# somewhere in my code
Trollop.educate_without_exiting
exit(N)
```

Is there a better way for me to exit with a code N of my choosing?

PS: I'm using Trollop for the first time and I really like it so far.  Thanks for the lib!

### PR DESCRIPTION
**Pull request by kbrock**
Not thrilled about changing `CommandLineError`, but seemed the best option

Fixes #57 

/cc @Fryguy @jaredbeck

### CODE REVIEW

**Comment by Fryguy** [comment]
:+1:

**Comment by jaredbeck** [comment]
This looks good, thanks!  Let's see if I understand the usage.  If we specify `educate_on_error` in the options block ..

```ruby
opts = Trollop.options %w(-f) do
  opt :x
  educate_on_error
end
# later, discover e.g. incorrect arguments ..
Trollop.die(arg, msg, error_code)
```

That will print `educate` to stderr and exit with the specified `error_code`?

**Comment by kbrock** [comment]
@jaredbeck yes

**Comment by kbrock** [comment]
to be picky, on your current example, it will die from -1 because argument `-f` is not supported.

If possible, I'm trying to avoid adding yet more and more flags. Do you need a custom return code for invalid argument?

Hoping to avoid a definition for each of the return codes.
An more for each of the required parameters that are not present etc.

Will this work for now?
After I pull options out into their own class, we may have more flexibility to the error return codes for each for each of the parameters

**Comment by jaredbeck** [comment]
@kbrock Thanks, with this, I am able to remove my monkey patch on trollop.

```diff
-# https://github.com/ManageIQ/trollop/issues/57
-module Trollop
-  def self.educate_without_exiting
-    @last_parser.educate($stderr)
-  end
-end
-
```

```diff
-        Trollop.educate_without_exiting
-        exit(E_USAGE)
+        Trollop.die("Please specify source file", nil, E_USAGE)
```

It feels like I'm doing something wrong though, passing the error message as the first argument to `die`.

If you want to see exactly how I'm using trollop, please check out the whole commit:

https://github.com/jaredbeck/minitest_to_rspec/commit/2b95071baeedd887a16c17b52fb11983f43224e1

**Comment by kbrock** [comment]
@jaredbeck Yea, that nil is ugly.

It looks like `die` was introduced for `die("arg1","should be positive")` but later because `die("need arg1 or arg2 when you have an arg3")`

With the block syntax for options, I'm not sure how necessary the argument parameter is. But I can't change that without risking breaking a lot of other code.
`arity` looks like a no go, but may be able to check if it is a `FixedNum`

Ideas?

**Comment by jaredbeck** [comment]
> I'm not sure how necessary the argument parameter is.

I don't see its value, either.

> I can't change that without risking breaking a lot of other code.

Yeah, maybe remove it in the next major version?

> arity looks like a no go, but may be able to check if it is a FixedNum.  Thoughts?

We could make `arg` optional, like this:

```
def die(arg = nil, msg = nil, error_code = nil)
  if arg && msg
    $stderr.puts "Error: argument --#{@specs[arg][:long]} #{msg}."
  elsif arg || msg
    $stderr.puts "Error: #{arg || msg}."
  else
    raise ArgumentError, "Expected arg or msg"
  end
  # ..
end
```

That way, I could at least avoid stuffing my message in `arg`.

Do you want a PR for that?  I'd be happy to.

**Comment by kbrock** [comment]
I would like to type:

```ruby
die("Missing argument, 5)
```

Hadn't thought about
```ruby
die(5)
```
```

**Comment by jaredbeck** [comment]
> Hadn't thought about
>
>     die(5)
>
> Are you suggesting keeping the parameters?
> 
>     die(nil, nil, 5)

Yes.  Dying without a specific message is a rare use case, and not very helpful to the end user.  In my experience, there's almost always some detail to provide in the event of a fatal error.  I'm not sure we should bother making that use case convenient, not in trollop 2.x anyway.

In trollop 3.x we could consider a new method signature, like:

```ruby
# A. simple, but inflexible
die(message, exit_status) 

# B. explicit and flexible, but verbose and requires ruby >= 2.0
die(message: nil, exit_status: nil) 

# C. explicit and flexible, but verbose, requires diligent documentation, and
# silently ignores incorrect options (e.g. typos).
die(options = {})
```

I prefer A or B.  In my experience, C is a poor choice.

**Comment by kbrock** [comment]
I want to get this right and in a backwards compatible way.
I would like to hold onto 1.8.7 as long as possible.

```ruby
die("oops") # => still defaults to -1
die("oops", 5)
die("arg1", "this was a bad argument", 5)
```

Would putting the error code first read much better?
Really wish we had uncovered this before merging, but since I haven't pushed the gem yet, we can get it in.

```ruby
die(5)
die("oops") # => -1 (current usage)
die(5, "oops")
die(5, "arg1", "this was a bad argument")
```

I'm just thinking about following the pattern:
```ruby
msg, error_code = nil, msg if msg.kind_of?(FixedNum)
```

**Comment by jaredbeck** [comment]
> Would putting the error code first read much better?

Either way looks fine to me.

> I just want to introduce one line and not touch arg

It's up to you.  I'd just keep it simple for now.  Don't worry about making the method signature as convenient as possible if you're just going to drop `arg` in trollop 3.

**Pull request merged**
