### PR TITLE
Option Type Registry, plus many other features

### PR DESCRIPTION
**Pull request by nanobowers**
- Merged in hidden-options and the refactor to pull out the Option class from kbrock and aryeh-looker's branches
- Added an option-type registry concept so that trollop could be extensible with user defined types.  This was a pretty significant code change.  Changed Option class to OptionDispatch, removed some constants and methods.  Changed api, but did not break any existing tests to do so.
- Added two parser-level settings to Parser.new: 
1. prevent default creation of short-options (as opposed to specifying :short=>:none for all of them
2. allow inexact match for long-options as long as the match is unambigious.  This is similar to Perl's Getopt::Long.  E.g: options :applesauce and :apricot are minimallly callable with --app and --apr.

All previous tests for trollop 2.1.x still pass, and tests have been added to cover new functionality, including some examples of user-defined registered types.  I regret the quantity of changes here, probably too much for one PR.

### CODE REVIEW

**Comment by kbrock** [comment]
@nanobowers this is getting pretty large.

Since there is a largeish base of users and the test suite is not organized in a way that I understand the coverage / holes, I've been hesitant on too many changes.

1. Do you have an idea how to do this in smaller chunks?
2. If there are certain PRs that you want merged, please just review / +1 them and we can get them in.

**Comment by nanobowers** [comment]
I'm new to this, so thanks for your patience.  I figured that the test suite was pretty comprehensive before embarking on this.  I'll add more tests if someone can provide a little bit of direction.

I'll try to split this into smaller PRs, _some_ of the elements are fairly easy to split out.  The unfortunately, the registry portion is a pretty big change and not easy to do without ripping up a lot of code.  Also, your Option-class change also contained quite a bit of code movement, which i leveraged.

As far as the Travis builds, i am not really sure what's going on with the integration issues.  I am using practically the same versions of rvm, ruby and bundler but not getting any test fails.  They seem to be due to a line wrapping issue, but i'm not totally sure.  From what I can tell, the 1.9.* builds are failing due to a dependency (tins) no longer supporting 1.9.*

**Comment by nanobowers** [comment]
Want to note that this may cover PR #7 and Issue #41 to some degree.

**Comment by kbrock** [comment]
already merged your #80, and after merging #66, should cut down on this PR a bunch

**Comment by nanobowers** [comment]
Will open a new one once @kbrock gets the option-class PR pulled in.

**Pull request closed without merging**
